import type { SolarSystemData } from '../src/data/types';

export const PLANET_COUNT_INVALID: SolarSystemData = {
  sun: {
    id: 'sun',
    name: 'Sun',
    type: 'sun',
    radiusKm: 100,
    orbitalDistanceKm: 0,
    orbitalPeriodDays: 0,
    rotationPeriodHours: 1,
    moons: [],
    hasRings: false,
    atmosphere: { present: false, description: '' },
    description: '',
    asset: {},
    visual: { sizeUnits: 1, orbitRadiusUnits: 0, orbitTilt: { x: 0, y: 0, z: 0 }, rotationSpeed: 0.1, orbitSpeed: 0 },
  },
  planets: [
    {
      id: 'p1',
      name: 'P1',
      type: 'planet',
      radiusKm: 100,
      orbitalDistanceKm: 100,
      orbitalPeriodDays: 1,
      rotationPeriodHours: 1,
      moons: [],
      hasRings: false,
      atmosphere: { present: false, description: '' },
      description: '',
      asset: {},
      visual: { sizeUnits: 0, orbitRadiusUnits: 10, orbitTilt: { x: 0, y: 0, z: 0 }, rotationSpeed: 0.1, orbitSpeed: 0.1 },
    },
    {
      id: 'p2',
      name: 'P2',
      type: 'planet',
      radiusKm: 100,
      orbitalDistanceKm: 200,
      orbitalPeriodDays: 2,
      rotationPeriodHours: 1,
      moons: [],
      hasRings: false,
      atmosphere: { present: false, description: '' },
      description: '',
      asset: {},
      visual: { sizeUnits: 1, orbitRadiusUnits: 10, orbitTilt: { x: 0, y: 0, z: 0 }, rotationSpeed: 0.1, orbitSpeed: 0.1 },
    },
  ],
  moons: [],
};
